overblog_graphql:
    definitions:
        schema:
            query: Query
#            resolver_maps:
#                - MyResolverMap
        mappings:
            auto_discover: false
            types:
                - type: yaml
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: ~

