version: '3'

services:
  app:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile-app
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      - CYCLOPOL_BASE_URI
      - CYCLOPOL_GEOCODER_BASE_URI
      - CYCLOPOL_DOWNLOAD_USER_AGENT
      - DATABASE_URL
      - APP_ENV
      - APP_DEBUG
    expose:
      - "9000"
    depends_on:
      - db
  proxy:
    image: "nginx:1.16-alpine"
    volumes:
      - "./infrastructure/proxy:/etc/nginx/conf.d"
      - ".:/usr/share/nginx"
    working_dir: /app # FIXME /usr/share/nginx ?
    ports:
      - "${PROXY_PORT}:80"
    depends_on:
      - app
  db:
    image: 'docker.io/mariadb:10.4.11'
    volumes:
      - cyclopol-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  ssg:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile-ssg
      args:
        UID: 1000
        GID: 1000
    volumes:
      - './ssg:/app'
    working_dir: /app
    command: "npm run dev"
    environment:
      PORT: "${NUXT_PORT}"
      HOST: 0.0.0.0
      GRAPHQL_BACKEND_URL: "http://proxy/graphql/"
      GRAPHQL_BROWSER_BACKEND_URL: "http://localhost:${PROXY_PORT}/graphql/"
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"
    depends_on:
      - proxy

volumes:
  cyclopol-db:

