version: '3'

services:
  cli:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile-cli
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      - CYCLOPOL_BASE_URI
      - CYCLOPOL_GEOCODER_BASE_URI
      - CYCLOPOL_DOWNLOAD_USER_AGENT
      - MYSQL_HOST=db
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  db:
    image: 'docker.io/mariadb:10.4.11'
    volumes:
      - cyclopol-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  ssg:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile-ssg
      args:
        UID: 1000
        GID: 1000
    volumes:
      - './ssg:/app'
    working_dir: /app
    command: "npm run dev"
    environment:
      PORT: "${NUXT_PORT}"
      HOST: 0.0.0.0
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"

volumes:
  cyclopol-db:

