Query:
  type: object
  config:
    description: "Articles ORM repository"
    fields:
      article:
        type: "Article"
        args:
          id:
            description: "Resolves using the article id."
            type: "Int"
        resolve: "@=resolver('Article', [args])"
      article_list:
        type: "[Article]"
        args:
          limit:
            description: "Maximum number of articles to return"
            type: "Int"
          search:
            description: "A search query to perform on the articles"
            type: "String"
        resolve: "@=resolver('ArticleList', [args])"
      article_count:
        args:
          search:
            description: "A search query to perform on the articles"
            type: "String"
        type: "[ArticleCount]"
        resolve: "@=resolver('ArticleCount', [args])"

